### PR TITLE
EranBot has been replaced by CopyPatrolBot

### PR DESCRIPTION
**Pull request by DreamRimmer**
EranBot has been replaced by CopyPatrolBot

### CODE REVIEW

**Comment by ChlodAlejandro** [comment]
Normally I'd be okay with merging a PR like this, but right now Copyvios is still [not configured](https://github.com/earwig/copyvios/blob/main/copyvios/turnitin.py#L11) to query CopyPatrol yet (and, to my knowledge, the current CopyPatrol backend doesn't have an API for getting active reports in JSON format yet). This has essentially made the "Use Turnitin" function ineffective. See [T354324](https://phabricator.wikimedia.org/T354324) for progress on that API (though I don't think it's one of CommTech's priorities as of now).

**Comment by earwig** [comment]
Yeah, I'd rather not reference CopyPatrolBot. We _should_ be using CopyPatrol's data, but we're not, and it would be misleading. We should probably remove the "Use Turnitin" option entirely until we can get that working.

**Comment by DreamRimmer** [comment]
Before I opened this PR, I knew that the current version of the code uses EranBot's API endpoints, so both the name and the API need to be updated. Since CopyPatrolBot's API is still in development, I thought it might be okay to mention it publicly for now. However, I've since realized that this probably wasn't the best idea.

**Comment by earwig** [comment]
No worries! I appreciate the contribution :)On Nov 14, 2024, at 11:46 AM, DR-WP ***@***.***> wrote:﻿
Before I opened this PR, I knew that the current version of the code uses EranBot's API endpoints, so both the name and the API need to be updated. Since CopyPatrolBot's API is still in development, I thought it might be okay to mention it publicly for now. However, I've since realized that this probably wasn't the best idea.

**Pull request closed without merging**
